apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mike
  name: mikedeployment
  labels:
    app: vwa
    tier: frontend
spec:
  selector: 
  selector: 
    matchLabels:
      app: vwa
      tier: frontend
  replicas: 4 
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 25%
         maxSurge: 1
  template:
    metadata:
      labels: 
        app: vwa
        tier: frontend
    spec:
      containers:
      - image: michaelbraunbass/testbadapp:latest
        imagePullPolicy: Always
        name: vwa
        ports:
        - containerPort: 8080
          name: vwa
---
apiVersion: v1
kind: Service
metadata:
  namespace: mike
  name: vwa-service
  labels:
    app: vwa
spec: 
  ports:
   - port: 80
     targetPort: 8080
  selector:
    app: vwa
    tier: frontend
  type: LoadBalancer

